#ifndef BOARD_ESP32_8048S043C_H
#define BOARD_ESP32_8048S043C_H

// Sunton ESP32-8048S043C: ESP32-S3 N16R8, 800x480 RGB LCD, GT911 touch.
#define BOARD_NAME "ESP32-8048S043C"

#define BOARD_HAS_RGB_LED 0
#define BOARD_HAS_TOUCH 1
#define TOUCH_CONTROLLER_GT911 1
#define LCD_PANEL_RGB 1

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480
#define LCD_WIDTH SCREEN_WIDTH
#define LCD_HEIGHT SCREEN_HEIGHT

// Render the 240x320 Mac framebuffer as 640x480, rotated clockwise and centered.
#define LCD_RENDER_SCALE 2
#define LCD_RENDER_ROTATE_CW 1
#define LCD_RENDER_OFFSET_X ((LCD_WIDTH - (DISP_HEIGHT * LCD_RENDER_SCALE)) / 2)
#define LCD_RENDER_OFFSET_Y ((LCD_HEIGHT - (DISP_WIDTH * LCD_RENDER_SCALE)) / 2)

// RGB LCD timing and pins from ESPHome's Sunton ESP32-8048S043C profile.
#define LCD_RGB_PCLK_HZ (16 * 1000 * 1000)
#define LCD_RGB_HSYNC_GPIO 39
#define LCD_RGB_VSYNC_GPIO 41
#define LCD_RGB_DE_GPIO 40
#define LCD_RGB_PCLK_GPIO 42
#define LCD_RGB_PCLK_ACTIVE_NEG 1
#define LCD_RGB_HSYNC_FRONT_PORCH 8
#define LCD_RGB_HSYNC_PULSE_WIDTH 4
#define LCD_RGB_HSYNC_BACK_PORCH 8
#define LCD_RGB_VSYNC_FRONT_PORCH 8
#define LCD_RGB_VSYNC_PULSE_WIDTH 4
#define LCD_RGB_VSYNC_BACK_PORCH 8

// RGB565 data bus order expected by esp_lcd RGB panel: B0..B4, G0..G5, R0..R4.
#define LCD_RGB_DATA0_GPIO 8
#define LCD_RGB_DATA1_GPIO 3
#define LCD_RGB_DATA2_GPIO 46
#define LCD_RGB_DATA3_GPIO 9
#define LCD_RGB_DATA4_GPIO 1
#define LCD_RGB_DATA5_GPIO 5
#define LCD_RGB_DATA6_GPIO 6
#define LCD_RGB_DATA7_GPIO 7
#define LCD_RGB_DATA8_GPIO 15
#define LCD_RGB_DATA9_GPIO 16
#define LCD_RGB_DATA10_GPIO 4
#define LCD_RGB_DATA11_GPIO 45
#define LCD_RGB_DATA12_GPIO 48
#define LCD_RGB_DATA13_GPIO 47
#define LCD_RGB_DATA14_GPIO 21
#define LCD_RGB_DATA15_GPIO 14

#define TFT_BL 2
#define TFT_RESET GPIO_UNUSED

#define TOUCH_I2C_PORT 0
#define TOUCH_I2C_SDA 19
#define TOUCH_I2C_SCL 20
#define TOUCH_I2C_FREQ_HZ 400000
#define TOUCH_GT911_ADDR1 0x5D
#define TOUCH_GT911_ADDR2 0x14
#define TOUCH_SWAP_XY 0
#define TOUCH_MIRROR_X 0
#define TOUCH_MIRROR_Y 0

#define TOUCH_DELTA_ROTATE_CW 1
#define TOUCH_DELTA_SCALE LCD_RENDER_SCALE

#define LED_R_PIN GPIO_UNUSED
#define LED_G_PIN GPIO_UNUSED
#define LED_B_PIN GPIO_UNUSED
#define GPIO_LED_PIN GPIO_UNUSED

#endif
